# Generated by Django 3.1.7 on 2021-03-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('image_width', models.IntegerField(max_length=5)),
                ('image_height', models.IntegerField(max_length=5)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
