# Generated by Django 3.1.7 on 2021-03-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resizerApp', '0002_auto_20210331_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='originalImages'),
        ),
    ]
