# Generated by Django 3.1.7 on 2021-04-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resizerApp', '0003_auto_20210331_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResizedImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('image_width', models.IntegerField()),
                ('image_height', models.IntegerField()),
                ('image', models.ImageField(upload_to='resizedImages')),
            ],
        ),
    ]
